---
title: "SK-5A4F_Mouse_DESEQ"
author: "Madison Carpenter"
date: "2023-06-28"
output: html_document
---

# 1.0 Setup the Environment

```{r Setup the Environment, echo=FALSE, message=FALSE}
suppressPackageStartupMessages({
# Load packages
library(tidyverse)
library(magrittr)
library(org.Mm.eg.db)
library(factoextra)
library(gt)
})

# Setup Pathways
workdir <- "XXXX"
scriptDir <- "XXXX"

# Set version control
set.seed(123)

# # Load DESeq workflow scripts
source(file = paste0(workdir,scriptDir,"DESeq.R"))
source(file = paste0(workdir,scriptDir,"DataVisualizations.R"))
source(file = paste0(workdir,scriptDir,"Deseq_Statistics.R"))
source(file = paste0(workdir,scriptDir, "pathway_graphs.R"))

# Set Diagram settings
options(width=200)
```

# 2.0 Figure 1B-C
## 2.1 Load Data: Xenon vs. Air
```{r pressure, echo=FALSE}
#_____________UPDATE!______________#
# Setup Variables
expdir <- "XXXXXX"

# Load Data
meta <- readxl::read_excel(paste0(workdir, expdir,"metadata.xlsx"))
quantfiles <- file.path(workdir,expdir,"transcripts_quant/", meta$Position, "quant.sf")
#_________________________________#
```

## 2.2 DESEQ
### 2.2.1 Modify Metadata 
```{r, echo=FALSE}
##________UPDATE ENTIRE SECTION___________##
# Set a file prefix
fileprefix <- "XXXXXX"

# Extract Samples Meta Data & Filter Outliers
sub_meta <- meta %>% filter(Genotype == "APPPS1")

# Pull specific Quant files
position_list <- paste0(sub_meta$Position, collapse = '|')
sample_files <- grep(position_list, quantfiles, value = TRUE) # Check number of files matches # of samples

# Check the metadata and files are in the correct order
all(file.exists(quantfiles))

## Create Graphs All 
graph_lab <- paste0(sub_meta$Position,"\n",sub_meta$Sex, "_", sub_meta$Genotype,"\n",sub_meta$CellType,"\n",sub_meta$Treatment)
table_lab <- paste0(sub_meta$Position,"_",sub_meta$Sex, "_", sub_meta$Genotype,"_",sub_meta$CellType,"_",sub_meta$Treatment)


# Format the Meta Data
table_header <- "APPPS1 Mouse: Xenon vs Air"
sub_meta %>%
  gt() %>% 
  tab_header(
    title = md("**Meta Data for samples**"),
    subtitle = md(paste0(table_header, " experiment's meta data are presented"))
  ) %>%
  cols_move_to_start(
    columns = c(Position, Treatment) # Update based on columns **
  )
```

### 2.2.2 Tximport/DESeq

```{r, echo=FALSE}
#_____________UPDATE!______________#
# Setup the Design for Tximport/DESeq2
design = "Treatment"
treatcolumn = "Treatment"
control = "AIR"
refanimal = "mouse"
type <- "LRT"
#_________________________________#

# Run Tx2gene
tx2gene <- tx2genefun(reference = refanimal)

# Run Tximport and DESeq 
ddsTxi1 <- Tximportfun(sample_files,reference = refanimal, metadata = sub_meta, design = design, tx2gene = tx2gene)
dds1 <- DESeqFun(treatcolumn = treatcolumn, control = control, DESeqObject = ddsTxi1, test_type = type)

# Save Deseq output
ddsobj <- dds1[[1]] # DESeq Object
ddsres <- dds1[[2]]# Results
```

### 2.2.3 Export DESEQ results

```{r}
#_____________UPDATE!______________#
resdir <- paste0(workdir,expdir,"XXXXXX")
#__________________________________#

# Extract the stats on the DESeq run 
extractedstats <-  extractstats(ddsobj, ContrastObj = ddsres ,sub_meta, graphlabel = table_lab)

# Save to variables
DEResults <- extractedstats[[1]] 
DEcounts <- extractedstats[[2]] 
sigDEResults <- extractedstats[[3]]
sigDEcounts <- extractedstats[[4]] 

summary(ddsres, alpha = 0.05)

# Export the Stats
exportstats(DEResults = DEResults, DEcounts = DEcounts,sigDEResults = sigDEResults, 
            sigDEcounts = sigDEcounts, directory = resdir,fileprefix = fileprefix)
```


## 2.3 Data Exploration
### 2.3.1 ScatterPlot Volcano (Figure 1B)

```{r}
# Setup Volcano Scatter Theme
theme_scatter <- theme(aspect.ratio = 1, 
                       panel.background = element_blank(),
                       panel.border=element_rect(fill=NA),
                       panel.grid.major = element_blank(),
                       panel.grid.minor = element_blank(),
                       strip.background=element_blank(),
                       axis.title  = element_text(size = 20, colour = "black"),
                       axis.text.x=element_text(colour="black",size =20),
                       axis.text.y=element_text(colour="black",size =20),
                       axis.ticks=element_line(colour="black"),
                       plot.margin=unit(c(1,1,1,1),"line"),
                       plot.title = element_text(colour="black",size =20))

  
# Setup Variables 
volcano <- DEResults %>% .[-1,]
volcano$log_pval <- -log10(volcano$pvalue)
sig_up_data <- volcano %>% filter(log2FoldChange > 0) %>% filter(pvalue < 0.05)
sig_down_data <- volcano %>% filter(log2FoldChange < 0) %>% filter(pvalue < 0.05)

# Setup Variables for genes to label
UP_genes <- c("Mertk","Tgfbr2","Adam22","Nr3c1","Tgfb1","Tgfbr1","Spi1")
UP_genes_data <- sig_up_data %>% filter(gene %in% UP_genes)

DOWN_genes <- c("Clu","Ifngr2","Ctsz","Calm3","Apoe","Nfkb1","Lgals3","Ccr1","Ccl5","Clec7a","Ccl2")
DOWN_genes_data <- sig_down_data %>% filter(gene %in% DOWN_genes)



# Scatter Volcano Plot
scatter <- ggplot(volcano, aes(x= log2FoldChange, y= log_pval, label = gene)) +
  geom_point(size=0.5, color = 'grey90') +
  geom_point(data = sig_up_data, color = 'red', size = 1)+
  geom_point(data = sig_down_data, color = 'dodgerblue3', size = 1) +
  theme_scatter +
  xlim(-5,5)+
  ylim(0,10) +
  geom_vline(xintercept = 0.15,colour="grey", linetype = "longdash") +
  geom_vline(xintercept = -0.15,colour="grey", linetype = "longdash") +
  geom_hline(yintercept = 1.3, colour="grey", linetype = "longdash") +
  labs(title = table_header,
       x = "Log2FC",
       y = "-log(pvalue)") +
    geom_text_repel(data = UP_genes_data,
                  color = 'black', size = 6,fontface = 'italic',
                  min.segment.length = 0,
                  nudge_y = 1.5,
                  nudge_x = 2 - abs(UP_genes_data$log2FoldChange),
                  max.overlaps = Inf,
                  box.padding = unit(0.5, 'mm'),
                  point.padding = unit(0.5, 'mm'),
                  direction = "y") +
  geom_text_repel(data = DOWN_genes_data,
                   color = 'black',size = 6, fontface = 'italic',
                   min.segment.length =0,
                   nudge_y = 2,
                   nudge_x = -3 + abs(DOWN_genes_data$log2FoldChange),
                   max.overlaps = Inf,
                   point.padding = unit(0.5, 'mm'),
                  direction = "y")


# Save Image
ggsave(filename = paste0(workdir, expdir, "plots/VolcanoPlots/", fileprefix, "GOI.pdf"),
  plot = scatter,
  device = NULL,
  path = NULL,
  scale = 1,
  width = NA,
  height = NA,
  units = c("mm"),
  dpi = 300,
  limitsize = TRUE,
  bg = NULL
)
```



### 2.3.2 IPA Dotplot (Figure 1C)

```{r}
##________UPDATE ENTIRE SECTION___________##
# Update the Paths for IPA graph output directory
IPAgraphdir <- paste0(workdir)
##________________________________________##

# Load IPA Data
IPAdata <- readxl::read_excel(path = "IPA File",sheet = "Sheet0",skip = 1) %>%
  dplyr::mutate(Experiment = paste0("APP.PS1_XenVsAir")) %>% dplyr::rename(c("Ingenuity.Canonical.Pathways" = "Ingenuity Canonical Pathways"), "z.score" = "z-score")

# Setup Pathways of interest
path.of.interest <- c(
"Role of CHK Proteins in Cell Cycle Checkpoint Control",
"Senescence Pathway",
"Synaptogenesis Signaling Pathway",
"Autophagy",
"iNOS Signaling",
"IL-1 Signaling",
"CCR5 Signaling in Macrophages",
"Oxidative Phosphorylation")

# Generate Graph of Interest
graph <- IPApoigraph_single(data = IPAdata, POI = path.of.interest, 
                            directory = IPAgraphdir, fileprefix = fileprefix, suffix = "poi")
```


