---
title: "SK_5A4F_IPMG_DESEQ"
author: "Madison Carpenter"
date: "2023-06-30"
output: html_document
---

# 1.0 Setup the Environment

```{r Setup the Environment, echo=FALSE, message=FALSE}
suppressPackageStartupMessages({
# Load packages
library(tidyverse)
library(magrittr)
library(org.Mm.eg.db)
library(factoextra)
library(gt)
})

# Setup Pathways
workdir <- "XXXX"
scriptDir <- "XXXX"

# Set version control
set.seed(123)

# # Load DESeq workflow scripts
source(file = paste0(workdir,scriptDir,"DESeq.R"))
source(file = paste0(workdir,scriptDir,"DataVisualizations.R"))
source(file = paste0(workdir,scriptDir,"Deseq_Statistics.R"))
source(file = paste0(workdir,scriptDir, "pathway_graphs.R"))

# Set Diagram settings
options(width=200)
```

# 2.0 Figure 4M-N Code
## 2.1 DESEQ
### 2.1.1 Load and Modify Data

```{r pressure, echo=FALSE}
#_____________UPDATE!______________#
#  Set to exp.directory
expdir <- paste0("XXXXXX")

# Load Data and Metadata
meta <- readxl::read_excel(paste0(workdir,expdir,"metadata.xlsx"))
quantfiles <- file.path(workdir,expdir,"transcripts_quant/", meta$Position, "quant.sf")
#_________________________________#
```

```{r, echo=FALSE}
##________UPDATE ENTIRE SECTION___________##
# Set a file prefix
fileprefix <- "XXXXXX" # Experimental group should be listed first in the file prefix**

# Extract Samples Meta Data
sub_meta <- meta %>% filter(Timepoint == "6M") %>% select(-Genotype) %>% mutate(Grouped = paste0(Position,"_", CellType,"_",Treatment))

# Pull specific Quant files
position_list <- paste0(sub_meta$Position, collapse = '|')
sample_files <- grep(position_list, quantfiles, value = TRUE) # Check number of files matches # of samples

# Check the metadata and files are in the correct order
## QC check - Order of metafile samples must match quant file order!  Fix metadata file if not!
all(file.exists(sample_files))


## Create Graphs All 
graph_lab <- sub_meta$Grouped

# Format the Meta Data
table_header <- "IPMG at 6 months"
sub_meta %>%
  gt() %>% 
  tab_header(
    title = md("**Meta Data for Sk-5A4F samples**"),
    subtitle = md(paste0(table_header, " experiment's meta data are presented"))
  ) %>%
  cols_move_to_start(
    columns = c(Position, CellType, Timepoint) # Update based on columns **
  )
```

### 2.1.2 Tximport/DESeq

```{r, echo=FALSE}
#_____________UPDATE!______________#
# Setup the Design for Tximport/DESeq2
design = "Treatment"
treatcolumn = "Treatment"
control = "AIR"
refanimal = "human"
type <- "LRT"
#_________________________________#
# Run Tx2gene
tx2gene <- tx2genefun(reference = refanimal)

# Run Tximport and DESeq 
ddsTxi <- Tximportfun(sample_files,reference = refanimal, metadata = sub_meta, design = design, tx2gene = tx2gene)
dds <- DESeqFun(treatcolumn = treatcolumn, control = control, DESeqObject = ddsTxi, test_type = type)

# Save Deseq output
ddsobj <- dds[[1]] # DESeq Object
ddsres <- dds[[2]]# Results
```

### 2.1.3 Export DESEQ results
```{r}
#_____________UPDATE!______________#
# Update to desired result directory
resdir <- paste0(workdir)
#__________________________________#

# Extract the stats on the DESeq run 
extractedstats <-  extractstats(DeseqObj = ddsobj, ContrastObj = ddsres ,sub_meta, graphlabel = graph_lab)

# Save to variables
DEResults <- extractedstats[[1]] 
DEcounts <- extractedstats[[2]] 
sigDEResults <- extractedstats[[3]]
sigDEcounts <- extractedstats[[4]] 

# Get Summary on DESEQ run
summary(ddsres, alpha = 0.05)

# Export the Stats
exportstats(DEResults = DEResults, DEcounts = DEcounts,sigDEResults = sigDEResults, 
            sigDEcounts = sigDEcounts, directory = resdir,fileprefix = fileprefix)
```

## 2.2 Data Exploration
### 2.2.1 Heatmap: Figure 4M

```{r}
##________Update_______##
heatmapdir <- paste0(workdir,expdir,"plots/Heatmap/")

#______________________#

# Generate HMAP for all significant genes
genheatmap(sigDEcounts, graph_lab = graph_lab, 
           height = 65, width = 10, suffix = paste0("_0.05pvalue.pdf"),
           directory = heatmapdir, fileprefix = fileprefix,
           cutrow = 2, gap_col = 5, show_row = TRUE)

# Generate HMAP for all significant genes - NO Label
genheatmap(sigDEcounts, graph_lab = graph_lab, 
           height = 65, width = 10, suffix = paste0("_NOLabel_0.05pvalue.pdf"),
           directory = heatmapdir, fileprefix = fileprefix,
           cutrow = 2, gap_col = 5, show_row = FALSE)
```


### 2.2.2 IPA Dotplot: Figure 4N
```{r}
##________UPDATE ENTIRE SECTION___________##
# Update to desired output directory
IPAgraphdir <- paste0(workdir)
##________________________________________##

# Load Data 
IPAdata <- xlsx::read.xlsx(file = "IPA File",sheetName = "Sheet0", startRow = 2) %>% 
  dplyr::mutate(Experiment = paste0("APP.PS1_XenVsAir")) %>% 
  rename("-log(p-value)" = "X..log.p.value.")

# Setup Pathways of interest
path.of.interest <- c(
"Role of PKR in Interferon Induction and Antiviral Response",
"Acute Phase Response Signaling",
"Death Receptor Signaling",
"Autophagy",
"NF-κB Activation by Viruses",
"PPAR Signaling",
"Actin Cytoskeleton Signaling",
"IL-10 Signaling")

# Generate Graph of Interest
IPApoigraph_single(data = IPAdata, POI = path.of.interest, directory = IPAgraphdir, fileprefix = fileprefix, suffix = "poi")
```
