---
title: "SK-4KD7_5CytokinesChamber"
author: "Madison Carpenter"
date: "2023-08-03"
output: html_document
---

* The code in this RMD file was used to generate Figures A & C in Supplementary Figures 5 *

# 1.0 Setup the Environment

```{r Setup the Environment, echo=FALSE, message=FALSE}
suppressPackageStartupMessages({
# Load packages
library(tidyverse)
library(magrittr)
library(xlsx)
library(gt)
})

# Setup Pathways
workdir <- "~/Dropbox (Partners HealthCare)/"
scriptDir <- "Scripts/BulkRNAseq/"

# Set version control
set.seed(123)

# # Load DESeq workflow scripts
source(file = paste0(workdir,scriptDir,"DESeq.R"))
source(file = paste0(workdir,scriptDir,"DataVisualizations.R"))
source(file = paste0(workdir,scriptDir,"Deseq_Statistics.R"))
source(file = paste0(workdir,scriptDir, "pathway_graphs.R"))

# Set Diagram settings
options(width=200)
```

# 2.0 Figure Supplementary 5A
## 2.1 Load Data
```{r pressure, ecdho=FALSE}
#_____________UPDATE!______________#
# Setup Variables
expdir <- "SK-4KD7_ZY-Human(bulkbrainAPOE)/"

# Load Data
meta <- readxl::read_excel(paste0(workdir, expdir,"metadata_5cyt_Chamber.xlsx")) %>% dplyr::rename("Position" = "Well")
meta$Treatment <- gsub(" ","",meta$Treatment)

quantfiles <- file.path(workdir,expdir,"transcripts_quant/", meta$Position, "quant.sf")
#_________________________________#
```



## 2.2 DESEQ
### 2.2.1 Modify Metadata 
```{r, echo=FALSE}
##________UPDATE ENTIRE SECTION___________##
# Set a file prefix
fileprefix <- "SK-4KD7_5Cyt_Chamber_Human_XenvsAir"

# Extract Samples Meta Data & Filter Outliers
sub_meta <- meta %>% mutate(Grouped = paste0(Position,"_",Gender,"_",Treatment,"_",Location,"_",Gas))

# Pull specific Quant files
position_list <- paste0(sub_meta$Position, collapse = '|')
sample_files <- grep(position_list, quantfiles, value = TRUE)

# Check the metadata and files are in the correct order
all(file.exists(quantfiles))

## Create Graphs All 
table_lab <- sub_meta$Grouped

# Format the Meta Data
table_header <- "Human 5 Cytokines Chamber: Xenon vs Air"
sub_meta %>%
  gt() %>% 
  tab_header(
    title = md("**Meta Data for Human SK-4KD7 samples**"),
    subtitle = md(paste0(table_header, " experiment's meta data are presented"))
  ) %>%
  cols_move_to_start(
    columns = c(Position, Treatment)
  )
```

### 2.2.2 Tximport/DESeq

```{r, echo=FALSE}
#_____________UPDATE!______________#
# Setup the Design for Tximport/DESeq2
design = "Gas"
treatcolumn = "Gas"
control = "Air"
refanimal = "human"
type <- "LRT"
#_________________________________#
# Run Tx2gene
tx2gene <- tx2genefun(reference = refanimal)

# Run Tximport and DESeq 
ddsTxi <- Tximportfun(sample_files,reference = refanimal, metadata = sub_meta, design = design, tx2gene = tx2gene)
dds <- DESeqFun(treatcolumn = treatcolumn, control = control, DESeqObject = ddsTxi, test_type = type)

# Save Deseq output
ddsobj <- dds[[1]] # DESeq Object
ddsres <- dds[[2]]# Results
```

### 2.2.3 Export DESEQ results

```{r}
#_____________UPDATE!______________#
# Update the result directory path
resdir <- paste0(workdir,expdir,"/results/5Cyt_Chamber/")
#__________________________________#

# Extract the stats on the DESeq run 
extractedstats <-  extractstats(ddsobj, ContrastObj = ddsres ,sub_meta, graphlabel = table_lab)

# Save to variables
DEResults <- extractedstats[[1]] 
DEcounts <- extractedstats[[2]] 
sigDEResults <- extractedstats[[3]]
sigDEcounts <- extractedstats[[4]] 

# Get summary on the deseq run
summary(ddsres, alpha = 0.05)

# Export the Stats
exportstats(DEResults = DEResults, DEcounts = DEcounts,sigDEResults = sigDEResults, 
            sigDEcounts = sigDEcounts, directory = resdir,fileprefix = fileprefix)
```

## 2.3 Data Exploration
### 2.3.1 Heatmaps

```{r}
#_____________UPDATE!______________#
heatmapdir <- paste0(workdir, expdir, "plots/heatmap/5Cyt_Chamber/")
#__________________________________#

# Generate Heatmap for significant genes
genheatmap(sigDEcounts, colnames(sigDEcounts)[-1], height = 200, width = 15, directory = heatmapdir, cutrow = 2, gap_col = c(3),fileprefix = fileprefix, suffix = "pvalue05.pdf", show_row = TRUE)

genheatmap(sigDEcounts, colnames(sigDEcounts)[-1], height = 200, width = 15, directory = heatmapdir, cutrow = 2, gap_col = c(3),fileprefix = fileprefix, suffix = "pvalue05_nolabels.pdf", show_row = FALSE)
```

# 3.0 Supplementary Figure 5C
## 3.1 Generate IPA DotPlot

```{r}
##________UPDATE ENTIRE SECTION___________##
fileprefix <- "SK-4KD7_5Cyt_Chamber_Human_XenvsAir"
IPAgraphdir <- paste0(workdir,expdir,"plots/IPA/5Cyt_Chamber/")
suffix <- "POI"
###_______________________________________####


# Construct IPA graph
IPAdata <- xlsx::read.xlsx(file = "~/Dropbox (Partners HealthCare)/SK-4KD7_ZY-Human(bulkbrainAPOE)/results/5Cyt_Chamber/SK-4KD7_5Cyt_Chamber_Human_XenvsAir_statistics_pval05_pathways.xlsx",sheetName = "Sheet0", startRow = 2) %>%
  dplyr::mutate(Experiment = paste0("5CytChamber_XenVsAir")) %>% dplyr::rename("-log(p-value)" = "X..log.p.value.")

# Setup Pathways of interest
path.of.interest <- c("Superpathway of Cholesterol Biosynthesis",
"IL-10 Signaling",
'MSP-RON Signaling in Macrophages Pathway',
'Orexin Signaling Pathway',
"PPAR Signaling",
"LXR/RXR Activation",
"Production of Nitric Oxide and Reactive Oxygen Species in Macrophages",
"Pyroptosis Signaling Pathway",
"Macrophage Classical Activation Signaling Pathway",
"IL-15 Production",
"iNOS Signaling",
"Pathogen Induced Cytokine Storm Signaling Pathway",
"Neuroinflammation Signaling Pathway")


# Generate Graph of Interest
graph <- IPApoigraph_single(data = IPAdata, POI = path.of.interest, fileprefix = fileprefix,
                            directory = IPAgraphdir, suffix = suffix, width = 5, height = 6, wrap = 30)

# View IPA Graph
graph
```